import type { TurkeyLocationSelection } from "@/features/locations/turkey-locations";
import type { MemoryItem, MemoryLocation } from "./types";

const images = {
  road: "https://images.unsplash.com/photo-1568569183126-fa052f4d0532?auto=format&fit=crop&fm=jpg&q=85&w=1400",
  hands: "https://images.unsplash.com/photo-1748288146170-7ab5a0e03d09?auto=format&fit=crop&fm=jpg&q=85&w=1200",
  flowers: "https://images.unsplash.com/photo-1768874020252-21d7cd0fad78?auto=format&fit=crop&fm=jpg&q=85&w=1200",
  coffee: "https://images.unsplash.com/photo-1773327230095-ad1def0f9989?auto=format&fit=crop&fm=jpg&q=85&w=1200",
  train: "https://images.unsplash.com/photo-1749236785892-a77b86650889?auto=format&fit=crop&fm=jpg&q=85&w=1400",
  embrace: "https://images.unsplash.com/photo-1759559584015-4600f0a0ec72?auto=format&fit=crop&fm=jpg&q=85&w=1400",
};

const prototypeVideo = "/prototype-video.mp4";

export const memoryItems: MemoryItem[] = [
  {
    id: "new-year-coffee",
    kind: "photo",
    date: "2026-01-11",
    dateLabel: "11 Ocak 2026",
    datePrecision: "day",
    title: "Bir pazar kahvesi",
    image: images.coffee,
    alt: "Ahşap masada bir fincan kahve",
    aspect: "square",
  },
  {
    id: "winter-note",
    kind: "text",
    date: "2026-01-11",
    dateLabel: "11 Ocak 2026",
    datePrecision: "day",
    title: "Sabah notu",
    body: "Aynı masada değildik ama kahvelerimiz yine aynı anda soğudu.",
    aspect: "note",
  },
  {
    id: "march-window",
    kind: "photo",
    date: "2026-03-06",
    dateLabel: "6 Mart 2026",
    datePrecision: "day",
    title: "Pencereden şehir",
    image: images.train,
    alt: "Tren penceresinden dışarı bakan kişi",
    aspect: "landscape",
  },
  {
    id: "spring-hands",
    kind: "video",
    date: "2026-04",
    dateLabel: "Nisan 2026",
    datePrecision: "month",
    title: "Nisan'dan kısa bir kayıt",
    image: images.hands,
    display: prototypeVideo,
    alt: "Gün batımında el ele tutuşan çift",
    aspect: "portrait",
  },
  {
    id: "urla-road",
    kind: "photo",
    date: "2026-05-15",
    dateLabel: "15 Mayıs 2026",
    datePrecision: "day",
    title: "Urla yolu",
    image: images.road,
    alt: "Denize bakan kıvrımlı sahil yolu",
    aspect: "landscape",
  },
  {
    id: "sunset-hands",
    kind: "video",
    date: "2026-05-15",
    dateLabel: "15 Mayıs 2026",
    datePrecision: "day",
    title: "Gün batmadan hemen önce",
    image: images.hands,
    display: prototypeVideo,
    alt: "Gün batımında el ele tutuşan çift",
    aspect: "portrait",
  },
  {
    id: "may-note",
    kind: "text",
    date: "2026-05-15",
    dateLabel: "15 Mayıs 2026",
    datePrecision: "day",
    title: "Bir cümle kalsın",
    body: "Yol uzundu ama ilk kez mesafenin bizi bir yere götürdüğünü hissettik.",
    aspect: "note",
  },
  {
    id: "wildflowers",
    kind: "photo",
    date: "2026-05-22",
    dateLabel: "22 Mayıs 2026",
    datePrecision: "day",
    title: "Masadaki kır çiçekleri",
    image: images.flowers,
    alt: "Vazoda renkli kır çiçekleri",
    aspect: "portrait",
  },
  {
    id: "coffee",
    kind: "photo",
    date: "2026-05-22",
    dateLabel: "22 Mayıs 2026",
    datePrecision: "day",
    title: "Soğuyan kahve",
    image: images.coffee,
    alt: "Ahşap masada bir fincan kahve",
    aspect: "square",
  },
  {
    id: "month-note",
    kind: "text",
    date: "2026-05",
    dateLabel: "Mayıs 2026",
    datePrecision: "month",
    title: "Mayıs'tan kalan",
    body: "Tam gününü unuttuk. Yağmurdan kaçarken aynı şarkıyı mırıldandığımızı unutmadık.",
    aspect: "note",
  },
  {
    id: "train",
    kind: "photo",
    date: "2026-05-28",
    dateLabel: "28 Mayıs 2026",
    datePrecision: "day",
    title: "Dönüş yolu",
    image: images.train,
    alt: "Tren penceresinden dışarı bakan kişi",
    aspect: "landscape",
  },
  {
    id: "beach-embrace",
    kind: "photo",
    date: "2026-05-30",
    dateLabel: "30 Mayıs 2026",
    datePrecision: "day",
    title: "Biraz daha kalalım",
    image: images.embrace,
    alt: "Sahilde gün batımında sarılan çift",
    aspect: "landscape",
  },
  {
    id: "summer-flowers",
    kind: "photo",
    date: "2026-08-09",
    dateLabel: "9 Ağustos 2026",
    datePrecision: "day",
    title: "Yol kenarından",
    image: images.flowers,
    alt: "Vazoda renkli kır çiçekleri",
    aspect: "portrait",
  },
  {
    id: "august-route",
    kind: "photo",
    date: "2026-08-09",
    dateLabel: "9 Ağustos 2026",
    datePrecision: "day",
    title: "İki şehir arası",
    image: images.road,
    alt: "Denize bakan kıvrımlı sahil yolu",
    aspect: "landscape",
  },
  {
    id: "year-letter",
    kind: "text",
    date: "2026",
    dateLabel: "2026",
    datePrecision: "year",
    title: "Bu yıl için",
    body: "Hangi gün olduğunu bilmesek de bu cümle bütün yıla ait: beklemek de hikâyemizin bir parçası.",
    aspect: "note",
  },
  {
    id: "undated-keepsake",
    kind: "photo",
    date: null,
    dateLabel: "Tarihsiz",
    datePrecision: "none",
    title: "Tarihi unutulan kare",
    image: images.embrace,
    alt: "Sahilde gün batımında sarılan çift",
    aspect: "square",
  },
];

export const locationsByDate: Record<string, MemoryLocation[]> = {
  "2026-01-11": [
    { id: "ankara-cankaya", label: "Ankara · Çankaya", coordinates: [32.8597, 39.9179] },
  ],
  "2026-03-06": [],
  "2026-05-15": [
    { id: "izmir-konak", label: "İzmir · Konak", coordinates: [27.1428, 38.4237] },
    { id: "izmir-urla", label: "İzmir · Urla", coordinates: [26.764, 38.3229] },
    { id: "izmir-cesme", label: "İzmir · Çeşme", coordinates: [26.3054, 38.3228] },
  ],
  "2026-05-22": [
    { id: "ankara-kavaklidere", label: "Ankara · Kavaklıdere", coordinates: [32.8611, 39.9081] },
  ],
  "2026-05-28": [],
  "2026-05-30": [
    { id: "antalya-konyaalti", label: "Antalya · Konyaaltı", coordinates: [30.6389, 36.8642] },
  ],
  "2026-08-09": [
    { id: "ankara", label: "Ankara", coordinates: [32.8597, 39.9334] },
    { id: "eskisehir", label: "Eskişehir · Odunpazarı", coordinates: [30.5206, 39.7667] },
  ],
};

export const locationSelectionsByDate: Record<string, TurkeyLocationSelection[]> = {
  "2026-01-11": [{ provinceCode: "06", districtCode: "1231" }],
  "2026-03-06": [],
  "2026-05-15": [
    { provinceCode: "35", districtCode: "1819" },
    { provinceCode: "35", districtCode: "1703" },
    { provinceCode: "35", districtCode: "1251" },
  ],
  "2026-05-22": [{ provinceCode: "06", districtCode: "1231" }],
  "2026-05-28": [],
  "2026-05-30": [{ provinceCode: "07", districtCode: "2038" }],
  "2026-08-09": [
    { provinceCode: "06" },
    { provinceCode: "26", districtCode: "2046" },
  ],
};
